### ISSUE TITLE
Unable to create an Owning Group with no include and no excludinig components.

### ISSUE THREAD

**Issue by Nomy1** [prime31/zig-ecs#14]
# Problem

Not able to create an Owning Group with no includes and no exludes.

```
pub const Position = struct { x: f32, y: f32 };

pub fn main() !void {
    var reg = ecs.Registry.init(std.heap.c_allocator);
    defer reg.deinit();

    var e = reg.create();
    reg.add(e, Position { .x = 1, .y = 1 });

    var group = reg.group(.{Position }, .{}, .{});   // <-----
}
```

# Result

fails assert in registry.zig: 471
`std.debug.assert(owned.len + includes.len + excludes.len > 1);`

Am I using the library incorrectly?

**Comment by prime31** [comment]
> Am I using the library incorrectly?
Yes. There is no point at all in creating an owning group of one component. It has no meaning. There is nothing to own. Just use a View or access the component storage directly for a single component.
