### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by RUSshy** [prime31/zig-ecs#15]
Hello, take this example:

```zig
const std = @import("std");
const ecs = @import("ecs");

// override the EntityTraits used by ecs
pub const EntityTraits = ecs.EntityTraitsType(.large);

pub const Test = struct { a: f32, b: i32 };

pub fn main() !void {
    var reg = ecs.Registry.init(std.testing.allocator);
    defer reg.deinit();

    while(true)
    {
        var e1 = reg.create();
        var e2 = reg.create();
        var e3 = reg.create();
        var e4 = reg.create();
        reg.add(e1,Test{ .a = 0, .b = 0 });
        reg.add(e2,Test{ .a = 0, .b = 0 });
        reg.add(e3,Test{ .a = 0, .b = 0 });
        reg.add(e4,Test{ .a = 0, .b = 0 });
        reg.destroy(e1);
        reg.destroy(e2);
        reg.destroy(e3);
        reg.destroy(e4);

        std.os.windows.kernel32.Sleep(1000);
    }
}
```

And watch the memory grow forever

I suspect the issue is with the SparseSet, it always reallocates pages

**Comment by RUSshy** [comment]
It seems to only happen with both ``.medium`` and ``.large`` ``EntityTraits``

**Comment by RUSshy** [comment]
i think the issue is Entity ID gets reused, so the version increments, therefore its value becomes bigger and bigger there requires all the time a new page since the index doesn't fit anymore

**Comment by RUSshy** [comment]
entt doesn't have this issue, i'll  try to check what they do under the hood, but reading their code base is a giant clusterfuck

**Comment by RUSshy** [comment]
oh i found it, you do not make proper use of the entity_mask/version_mask, and page size is always way different than entt

this example with entt sticks at 700kb of memory usage; they properly recycle ids too

**Comment by RUSshy** [comment]
when doing proper entity id management + same page management as entt for sparse set, the memory leak disapears

at least in the D port version https://github.com/ryuukk/decs

**Comment by RUSshy** [comment]
https://github.com/prime31/zig-ecs/blob/master/src/ecs/sparse_set.zig#L22

Here uses SparseT max -> StarseT is u64

But here it uses IndexType max -> IndexType is u32

So entities gets never reused, that's my guess

**Comment by RUSshy** [comment]
and boom, memory fix solved! i'll send a PR

**Comment by RUSshy** [comment]
![image](https://user-images.githubusercontent.com/18348637/126036506-75edcc38-6d18-454b-b2ca-eedeec3f7a85.png)

entities properly recycled and memory remains unchanged

**Comment by Avokadoen** [comment]
Nice work!
